# Generated by Django 2.2.6 on 2019-10-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('calories', models.IntegerField(null=True)),
                ('spicy', models.IntegerField(choices=[(1, 'no spicy'), (2, 'some spicy'), (3, 'spicy'), (4, 'very spicy'), (5, 'ultra spicy')])),
                ('meat', models.IntegerField(choices=[(1, 'with meat'), (2, 'vegetarian'), (3, 'vegan')])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('allergenes', models.ManyToManyField(to='restaurant.Allergene')),
            ],
        ),
    ]
